name: Check PR

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Check Formatting
      run: |
        npm run fmt

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Build
      run: |
        npm run build
